const CONFIG = {
  // Replace this with the real support mailbox before publishing.
  supportEmail: "REPLACE_WITH_SUPPORT_EMAIL"
};

const SECTIONS = {
  neuronode: {
    icon: "🧠", eyebrow: "NEURONODE & AAC", title: "NeuroNode & AAC Support",
    description: "Guided help for common NeuroNode connection, power, status-light, setup and AAC access questions.",
    issues: [
      { title:"NeuroNode won't connect", desc:"Bluetooth searching, reconnecting or Controller App connection issues.", flow:"nn-connect", tag:"COMMON" },
      { title:"What do the lights mean?", desc:"Understand blue, red, green and yellow status indications.", flow:"nn-lights", tag:"QUICK GUIDE" },
      { title:"NeuroNode Duo setup", desc:"Windows setup: power on, Controller App, placement, Grid 3 and start.", flow:"nn-setup", tag:"SETUP" },
      { title:"NeuroNode has no light", desc:"Run basic power and charging checks before escalating.", flow:"nn-power", tag:"TROUBLESHOOT" },
      { title:"Grid 3 doesn't respond", desc:"If NeuroNode connects but Grid 3 does not respond, check the Grid 3 switch connection.", flow:"grid-connect", tag:"GRID 3" },
      { title:"NeuroNode accessories", desc:"Review common NeuroNode Duo trial accessories and return checklist items.", article:"nn-accessories", tag:"CHECKLIST" }
    ]
  },
  grid3: {
    icon:"🖥️", eyebrow:"GRID 3", title:"Grid 3 Support",
    description:"Frontline help for NeuroNode-to-Grid 3 switch connection and access configuration.",
    issues:[
      { title:"Connect NeuroNode to Grid 3", desc:"Menu → Settings → Access → Switches → Connection → Change Key.", flow:"grid-connect", tag:"COMMON" },
      { title:"Grid 3 not detecting NeuroNode", desc:"Separate a Grid 3 configuration issue from a NeuroNode connection issue.", flow:"grid-detect", tag:"TROUBLESHOOT" },
      { title:"NeuroNode works in Controller App only", desc:"Confirm activation and then check the Grid 3 access pathway.", flow:"grid-controller", tag:"DIAGNOSTIC" },
      { title:"Open Grid 3 during NeuroNode setup", desc:"See where Grid 3 sits in the standard NeuroNode Duo setup flow.", flow:"nn-setup", tag:"SETUP" }
    ]
  },
  neurostrip: {
    icon:"📈", eyebrow:"NEUROSTRIP", title:"NeuroStrip Help Centre",
    description:"A simple first-line area for common NeuroStrip setup, usage and data questions. More approved content can be added as your NeuroStrip guides are finalised.",
    issues:[
      { title:"Getting started", desc:"Choose the type of NeuroStrip help you need.", flow:"strip-start", tag:"START HERE" },
      { title:"Connection issue", desc:"Run basic connection checks and escalate if the standard process does not resolve it.", flow:"strip-connect", tag:"TROUBLESHOOT" },
      { title:"Data & analysis", desc:"Understand where NeuroStrip data guidance belongs and what should be escalated.", article:"strip-data", tag:"GUIDE" },
      { title:"Research / product enquiry", desc:"General NeuroStrip capability questions and route to the appropriate team where needed.", article:"strip-research", tag:"GENERAL" }
    ]
  },
  general: {
    icon:"◈", eyebrow:"CONTROL BIONICS", title:"General Enquiries",
    description:"Use this section when the customer does not know which product/support area they need.",
    issues:[
      { title:"I need a manual", desc:"Route to the correct product guide or quick-start information.", article:"manuals", tag:"RESOURCES" },
      { title:"I don't know which support area", desc:"A simple product triage to get the customer to the right section.", flow:"general-route", tag:"ROUTING" },
      { title:"Trial device help", desc:"Setup and return guidance can be surfaced from approved trial cards.", article:"trials", tag:"TRIALS" },
      { title:"Contact Support", desc:"Escalate a non-standard issue with a concise summary.", flow:"general-escalate", tag:"CONTACT" }
    ]
  }
};

const ARTICLES = {
  "nn-accessories": { area:"NeuroNode & AAC", title:"NeuroNode Duo accessories", summary:"A quick visual checklist for common NeuroNode Duo trial equipment.", image:"assets/page_23.png", body:`<h3>Common items</h3><ul><li>NeuroNode Duo device</li><li>Device charger</li><li>NeuroNode</li><li>NeuroNode charging plate</li><li>NeuroNode charging cord</li><li>Accessories bag</li></ul><p>Use the approved trial checklist when confirming what was sent and what should be returned.</p>` },
  "strip-data": { area:"NeuroStrip", title:"NeuroStrip data & analysis", summary:"V1 keeps this area conservative until the approved NeuroStrip technical guides are loaded into the platform.", image:"assets/page_47.png", body:`<h3>What V1 can do</h3><p>Route users to approved NeuroStrip information about sessions, telemetry, connection and data analysis.</p><h3>What V1 should not improvise</h3><p>Clinical interpretation, diagnosis, treatment recommendations or unsupported claims should not be generated by this static assistant.</p><p>Add approved NeuroStrip screenshots and technical articles here as they are finalised.</p>` },
  "strip-research": { area:"NeuroStrip", title:"NeuroStrip research & product enquiries", summary:"Frontline product questions can be answered from approved materials; detailed study design or clinical interpretation should be routed appropriately.", image:"assets/page_47.png", body:`<h3>Good frontline topics</h3><ul><li>What NeuroStrip is designed to measure</li><li>General connectivity and wearability</li><li>Where to find product documentation</li><li>General data export / analysis resources</li></ul><h3>Escalate when needed</h3><p>Use human support for requests that depend on study-specific methodology, unsupported claims or detailed clinical interpretation.</p>` },
  manuals: { area:"General Enquiries", title:"Manuals & quick-start guides", summary:"The trial cards already contain QR-linked quick-start and information resources for multiple Control Bionics products.", image:"assets/page_21.png", body:`<h3>V1 behaviour</h3><p>Select a product and operating system, then present the correct approved guide. For this prototype, the NeuroNode Duo Windows easy-read setup guide is included as an example.</p><p>As more guides are approved, add them to the assets folder and link them through the knowledge entries in <strong>app.js</strong>.</p>` },
  trials: { area:"General Enquiries", title:"Trial device guidance", summary:"The same platform can support customers from initial setup through to the return checklist.", image:"assets/page_23.png", body:`<h3>Possible trial journey</h3><ol><li>Identify the trial device.</li><li>Show the correct setup card.</li><li>Surface common troubleshooting during the trial.</li><li>At the end, show the correct accessories return checklist.</li></ol><p>This reduces the need to repeatedly resend the same setup and return instructions.</p>` }
};

const FLOWS = {
  "nn-connect": {
    area:"NeuroNode & AAC", title:"NeuroNode won't connect", intro:"We'll run the standard connection checks first and only escalate if they fail.",
    steps:[
      { title:"What is the NeuroNode doing?", copy:"Choose the closest status. This helps route the next check.", image:"assets/page_37.png", caption:"Reference: NeuroNode status light guide.", options:[
        {label:"🔵 Flashing blue", next:1, note:"Blue flashing / Bluetooth searching"},
        {label:"🔴 Red light", next:1, note:"Red error state"},
        {label:"No light", jump:"nn-power"},
        {label:"I'm not sure", next:1, note:"Status light unclear"}
      ]},
      { title:"Perform a Bluetooth reset / scrub", copy:"If the Controller App is available, use the app reset method. The manual method can be used when needed.", bullets:["Close the NeuroNode Controller App if using the manual method.","Forget/delete NeuroNode from Bluetooth settings if present.","Turn Bluetooth off on the Windows or iOS device.","Use the supplied push pin to press and hold the reset button.","Release when the light changes to rapid blue flashing.","Wait for the blue flashing to stop, then turn Bluetooth back on and reconnect."], image:"assets/page_39.png", caption:"Reference: approved Bluetooth Reset / Scrub trial card.", options:[
        {label:"✓ It connected", resolve:"Bluetooth reset restored the connection."},
        {label:"Still not connecting", next:2, note:"Bluetooth reset completed — unresolved"}
      ]},
      { title:"Check the NeuroNode Controller App", copy:"Open the Controller App, shake the NeuroNode to wake it, then select Connect to NeuroNode.", image:"assets/page_21.png", caption:"Reference: NeuroNode Duo Windows setup guide.", options:[
        {label:"Controller App connects", jump:"grid-detect", note:"Controller App connection successful"},
        {label:"Controller App cannot find it", escalate:"Controller App cannot find NeuroNode after Bluetooth reset"},
        {label:"It connected after this", resolve:"Controller App reconnection restored communication."}
      ]}
    ]
  },
  "nn-lights": {
    area:"NeuroNode & AAC", title:"NeuroNode status lights", intro:"A quick reference for the common NeuroNode signal indicators.",
    steps:[{ title:"Choose the light colour", copy:"The trial-card guide describes the following status indicators.", image:"assets/page_37.png", caption:"Reference: NeuroNode Signal Indicators.", options:[
      {label:"🔵 Blue", message:"Blue indicates the NeuroNode is searching for a Bluetooth connection and will return to standby if none is found.", next:1},
      {label:"🔴 Red", message:"Red indicates an error state. Use the approved Reset/Bluetooth Scrub process or contact support if it persists.", jump:"nn-connect"},
      {label:"🟢 Green", message:"Green indicates an EMG/spatial signal has been detected and counted as a switch.", resolve:"Status light explanation completed."},
      {label:"🟡 Yellow", message:"Yellow indicates low battery; recharging is recommended.", resolve:"Status light explanation completed."}
    ]},{ title:"Blue means Bluetooth searching", copy:"If the device is not reconnecting, continue into the standard Bluetooth reset / scrub flow.", image:"assets/page_39.png", caption:"Bluetooth Reset / Scrub", options:[{label:"Start reset steps", jump:"nn-connect"},{label:"That's all I needed", resolve:"Status light explanation completed."}]}]
  },
  "nn-setup": {
    area:"NeuroNode & AAC", title:"NeuroNode Duo setup — Windows", intro:"A simple five-step setup based on the existing Easy Read trial card.",
    steps:[
      {title:"Turn on the device",copy:"Press and hold the power button until the screen lights up.",image:"assets/page_21.png",options:[{label:"Next",next:1}]},
      {title:"Open NeuroNode Controller",copy:"Open the NeuroNode Controller App, shake to wake the NeuroNode and connect to NeuroNode.",image:"assets/page_21.png",options:[{label:"Next",next:2}]},
      {title:"Place the NeuroNode",copy:"Place the NeuroNode on the designated area on the user using the approved setup/placement guidance.",image:"assets/page_21.png",options:[{label:"Next",next:3}]},
      {title:"Open Grid 3",copy:"Open Grid 3 or the relevant AAC software.",image:"assets/page_21.png",options:[{label:"Next",next:4}]},
      {title:"Get started",copy:"For advanced NeuroNode settings, refer to the approved Quick Start Guide.",image:"assets/page_21.png",options:[{label:"Done",resolve:"NeuroNode Duo setup guide completed."}]}
    ]
  },
  "nn-power": {
    area:"NeuroNode & AAC", title:"NeuroNode has no light", intro:"Run basic power checks before treating this as a device fault.",
    steps:[{title:"Check charging and power",copy:"Confirm the charging plate/cable/charger and wall outlet have power, and make sure the NeuroNode is seated correctly.",bullets:["Try a known-working power outlet.","Inspect the cable and charger for obvious damage.","Confirm the charging plate is connected correctly."],options:[{label:"It powers on now",resolve:"Power/charging check restored operation."},{label:"Still no light",escalate:"No LED response after standard power and charging checks"}]}]
  },
  "grid-connect": {
    area:"Grid 3", title:"Connect NeuroNode to Grid 3", intro:"Set the NeuroNode as the switch connection used by Grid 3 scanning mode.",
    steps:[
      {title:"Open Switch settings",copy:"In Grid 3, go to Menu → Settings → Access → Switches.",image:"assets/page_34.png",caption:"Reference: Grid 3 connection trial card.",options:[{label:"Next",next:1}]},
      {title:"Choose Connection",copy:"In Switches, choose Connection, then select Change Key.",image:"assets/page_34.png",options:[{label:"Next",next:2}]},
      {title:"Activate NeuroNode",copy:"Use the NeuroNode to make a selection, then press OK. Press OK once more to save the changes.",image:"assets/page_34.png",options:[{label:"✓ Grid 3 responds now",resolve:"Grid 3 switch connection configured successfully."},{label:"Grid 3 still doesn't respond",jump:"grid-detect",note:"Grid 3 connection settings completed — unresolved"}]}
    ]
  },
  "grid-detect": {
    area:"Grid 3", title:"Grid 3 is not detecting NeuroNode", intro:"First determine whether the problem is NeuroNode communication or Grid 3 configuration.",
    steps:[{title:"Does NeuroNode work in the Controller App?",copy:"Open NeuroNode Controller and confirm whether the NeuroNode connects and activation is detected.",image:"assets/page_21.png",options:[{label:"Yes — Controller App works",next:1,note:"NeuroNode functional in Controller App"},{label:"No — Controller App doesn't work",jump:"nn-connect",note:"NeuroNode not working in Controller App"}]},{title:"Recheck Grid 3 switch connection",copy:"Go to Menu → Settings → Access → Switches → Connection → Change Key. Activate NeuroNode and save with OK.",image:"assets/page_34.png",options:[{label:"✓ Working now",resolve:"Grid 3 connection was corrected."},{label:"Still not working",escalate:"NeuroNode works in Controller App but Grid 3 remains unresponsive after switch configuration"}]}]
  },
  "grid-controller": { area:"Grid 3", title:"Controller App works, Grid 3 does not", intro:"This usually points the frontline check toward Grid 3 access configuration.", steps:[{title:"Confirm Grid 3 switch connection",copy:"Use the documented Switches → Connection → Change Key pathway and activate NeuroNode once to assign the key.",image:"assets/page_34.png",options:[{label:"Working now",resolve:"Grid 3 access connection corrected."},{label:"Still not working",escalate:"Controller App detects NeuroNode but Grid 3 remains unresponsive"}]}] },
  "strip-start": { area:"NeuroStrip", title:"NeuroStrip help", intro:"Choose the type of help you need. This V1 only includes conservative frontline routing until more approved NeuroStrip guides are loaded.", steps:[{title:"What do you need help with?",copy:"Choose the closest topic.",image:"assets/page_47.png",options:[{label:"Connection problem",jump:"strip-connect"},{label:"Data / analysis",article:"strip-data"},{label:"Research / product question",article:"strip-research"},{label:"Something else",escalate:"NeuroStrip enquiry outside current V1 knowledge base"}]}] },
  "strip-connect": { area:"NeuroStrip", title:"NeuroStrip connection issue", intro:"V1 performs only basic frontline checks until approved technical troubleshooting content is added.", steps:[{title:"Basic connection check",copy:"Confirm the device is powered, the relevant app/device Bluetooth is available, and retry the approved connection workflow.",image:"assets/page_47.png",options:[{label:"Connected now",resolve:"Basic NeuroStrip connection check resolved the issue."},{label:"Still not connecting",escalate:"NeuroStrip connection issue unresolved by current approved V1 checks"}]}] },
  "general-route": { area:"General Enquiries", title:"Find the right support area", intro:"Choose what the customer is using or asking about.", steps:[{title:"Which area is this about?",copy:"Select the closest option.",options:[{label:"NeuroNode / AAC",jump:"nn-connect"},{label:"Grid 3",jump:"grid-connect"},{label:"NeuroStrip",jump:"strip-start"},{label:"Not sure",escalate:"General enquiry cannot be routed from current information"}]}] },
  "general-escalate": { area:"General Enquiries", title:"Contact Support", intro:"Use this for a question that is not covered by the current frontline knowledge base.", steps:[{title:"Escalate the enquiry",copy:"The platform will generate a basic summary for Support.",options:[{label:"Prepare support summary",escalate:"General enquiry requires human support"}]}] }
};

let currentSection = null;
let currentFlowId = null;
let currentStep = 0;
let caseNotes = [];

const views = ["homeView","sectionView","flowView","articleView","escalateView"];
const byId = id => document.getElementById(id);
function showView(id){ views.forEach(v=>byId(v).classList.toggle("active",v===id)); window.scrollTo({top:0,behavior:"smooth"}); }

function openSection(id){
  currentSection=id; const s=SECTIONS[id];
  byId("sectionIcon").textContent=s.icon; byId("sectionEyebrow").textContent=s.eyebrow; byId("sectionTitle").textContent=s.title; byId("sectionDescription").textContent=s.description;
  const grid=byId("issueGrid"); grid.innerHTML="";
  s.issues.forEach(i=>{ const b=document.createElement("button"); b.className="issue-card"; b.type="button"; b.innerHTML=`<div class="tag">${i.tag}</div><h3>${i.title}</h3><p>${i.desc}</p>`; b.addEventListener("click",()=> i.flow ? startFlow(i.flow) : openArticle(i.article)); grid.appendChild(b); });
  showView("sectionView");
}

function startFlow(id){ currentFlowId=id; currentStep=0; caseNotes=[]; renderFlow(); showView("flowView"); }
function renderFlow(){
  const f=FLOWS[currentFlowId], step=f.steps[currentStep];
  byId("flowArea").textContent=f.area.toUpperCase(); byId("flowTitle").textContent=f.title; byId("flowIntro").textContent=f.intro;
  byId("progressBar").style.width=`${Math.max(8,((currentStep+1)/f.steps.length)*100)}%`;
  let html=`<div class="step-number">STEP ${currentStep+1} OF ${f.steps.length}</div><div class="step-title">${step.title}</div><div class="step-copy">${step.message ? `<strong>${step.message}</strong><br><br>` : ""}${step.copy||""}</div>`;
  if(step.bullets) html+=`<ul class="check-list">${step.bullets.map(x=>`<li>✓ ${x}</li>`).join("")}</ul>`;
  byId("flowContent").innerHTML=html;
  const v=byId("visualContent"); v.innerHTML=step.image ? `<img src="${step.image}" alt="Visual support guide"><p>${step.caption||"Approved visual guide used as reference."}</p>` : `<div style="padding:44px 16px"><div style="font-size:44px">↳</div><h3>Guided support</h3><p>This step does not require a visual yet. Add an approved image later if helpful.</p></div>`;
  const actions=byId("flowActions"); actions.innerHTML="";
  (step.options||[]).forEach((o,idx)=>{ const b=document.createElement("button"); b.type="button"; b.textContent=o.label; if(idx===0)b.classList.add("primary"); b.addEventListener("click",()=>handleOption(o)); actions.appendChild(b); });
}

function handleOption(o){
  if(o.note) caseNotes.push(o.note);
  if(o.message) caseNotes.push(o.message);
  if(o.resolve){ caseNotes.push("Resolved: "+o.resolve); showResolution(o.resolve); return; }
  if(o.escalate){ caseNotes.push(o.escalate); openEscalation(o.escalate); return; }
  if(o.jump){ startFlow(o.jump); return; }
  if(o.article){ openArticle(o.article); return; }
  if(Number.isInteger(o.next)){ currentStep=o.next; renderFlow(); }
}

function showResolution(text){
  byId("flowContent").innerHTML=`<div class="step-number">RESOLVED</div><div class="step-title">✓ Issue resolved</div><div class="step-copy">${text}</div>`;
  byId("progressBar").style.width="100%"; byId("visualContent").innerHTML=`<div style="padding:44px 16px"><div style="font-size:48px">✓</div><h3>Frontline support complete</h3><p>No human support is required unless the issue returns or the customer has another question.</p></div>`;
  byId("flowActions").innerHTML=""; const b=document.createElement("button"); b.className="primary"; b.textContent="Back to support home"; b.addEventListener("click",()=>showView("homeView")); byId("flowActions").appendChild(b);
}

function openArticle(id){ const a=ARTICLES[id]; byId("articleArea").textContent=a.area.toUpperCase(); byId("articleTitle").textContent=a.title; byId("articleSummary").textContent=a.summary; byId("articleBody").innerHTML=`<div class="article-body">${a.body}</div>`; byId("articleVisual").innerHTML=a.image?`<img src="${a.image}" alt="Reference guide"><div class="caption">Visual reference from the existing Control Bionics trial-card material.</div>`:""; showView("articleView"); }

function openEscalation(reason){
  const flow=FLOWS[currentFlowId]; const summary=`Area: ${flow?.area||"General"}\nIssue: ${flow?.title||"General enquiry"}\n\nTroubleshooting / information captured:\n${caseNotes.length?caseNotes.map(x=>"• "+x).join("\n"):"• Standard V1 frontline pathway completed"}\n\nEscalation reason:\n${reason}\n\nResult: Unresolved — human support recommended.`;
  byId("caseSummary").textContent=summary; byId("caseSummary").dataset.raw=summary; showView("escalateView");
}

function performSearch(){
  const q=byId("globalSearch").value.trim().toLowerCase(); const box=byId("searchResults"); if(!q){box.classList.remove("show");return;}
  const candidates=[];
  Object.entries(FLOWS).forEach(([id,f])=>candidates.push({type:"flow",id,title:f.title,desc:f.intro,hay:(f.title+" "+f.intro+" "+f.area).toLowerCase()}));
  Object.entries(ARTICLES).forEach(([id,a])=>candidates.push({type:"article",id,title:a.title,desc:a.summary,hay:(a.title+" "+a.summary+" "+a.area).toLowerCase()}));
  const words=q.split(/\s+/).filter(w=>w.length>2); let scored=candidates.map(c=>({...c,score:words.reduce((n,w)=>n+(c.hay.includes(w)?1:0),0)})).filter(c=>c.score>0).sort((a,b)=>b.score-a.score).slice(0,6);
  // Simple intent shortcuts for the most common support language.
  if(q.includes("flashing blue")||q.includes("won't connect")||q.includes("wont connect")||q.includes("bluetooth")) scored=[{type:"flow",id:"nn-connect",title:"NeuroNode won't connect",desc:"Run Bluetooth reset / scrub and Controller App checks",score:99},...scored.filter(x=>x.id!=="nn-connect")];
  if(q.includes("grid")&&(q.includes("detect")||q.includes("respond")||q.includes("switch"))) scored=[{type:"flow",id:"grid-detect",title:"Grid 3 is not detecting NeuroNode",desc:"Check Controller App first, then Grid 3 switch configuration",score:99},...scored.filter(x=>x.id!=="grid-detect")];
  box.innerHTML=""; box.classList.add("show");
  if(!scored.length){ const b=document.createElement("button");b.className="search-result";b.innerHTML="<strong>No exact V1 match</strong><span>Open General Enquiries to route this question.</span>";b.addEventListener("click",()=>openSection("general"));box.appendChild(b);return;}
  scored.slice(0,5).forEach(r=>{ const b=document.createElement("button");b.className="search-result";b.innerHTML=`<strong>${r.title}</strong><span>${r.desc}</span>`;b.addEventListener("click",()=>r.type==="flow"?startFlow(r.id):openArticle(r.id));box.appendChild(b); });
}

byId("searchBtn").addEventListener("click",performSearch); byId("globalSearch").addEventListener("keydown",e=>{if(e.key==="Enter")performSearch();});
document.querySelectorAll("[data-section]").forEach(b=>b.addEventListener("click",()=>openSection(b.dataset.section)));
document.querySelectorAll("[data-flow]").forEach(b=>b.addEventListener("click",()=>startFlow(b.dataset.flow)));
byId("homeBtn").addEventListener("click",()=>showView("homeView")); byId("sectionBack").addEventListener("click",()=>showView("homeView")); byId("flowBack").addEventListener("click",()=>currentSection?openSection(currentSection):showView("homeView")); byId("articleBack").addEventListener("click",()=>currentSection?openSection(currentSection):showView("homeView")); byId("escalateBack").addEventListener("click",()=>showView("flowView")); byId("restartFlow").addEventListener("click",()=>startFlow(currentFlowId));
byId("copySummary").addEventListener("click",async()=>{ try{await navigator.clipboard.writeText(byId("caseSummary").dataset.raw);byId("copyStatus").textContent="Summary copied."}catch{byId("copyStatus").textContent="Copy is blocked in this browser. Select the summary text manually."} });
byId("emailSupport").addEventListener("click",()=>{ const raw=byId("caseSummary").dataset.raw||""; if(CONFIG.supportEmail==="REPLACE_WITH_SUPPORT_EMAIL"){alert("Before publishing, replace CONFIG.supportEmail in app.js with the Control Bionics support mailbox.");return;} window.location.href=`mailto:${encodeURIComponent(CONFIG.supportEmail)}?subject=${encodeURIComponent("Control Bionics Support Escalation")}&body=${encodeURIComponent(raw)}`; });
